#!/usr/bin/env bash
# Regenerate the test media and assets.js. Deterministic; needs ffmpeg with
# libopus and python3 (standard library only).
#
# Two clips, each encoded ONCE and then remuxed, so the WebM, the fMP4 and the
# raw packet list in assets.js carry byte-identical Opus packets and a decode
# surface that refuses one of them cannot be blamed on the container:
#
#   opus16   16 channels, channel k carries a sine at 200 + 100 k Hz, so a
#            decoder that reorders, drops or downmixes channels is caught by
#            the page's per-channel tone check. Channel mapping family 255
#            (independent streams, no assigned channel meaning), which is
#            how this stream carries 16 channels; RFC 8486 defines families
#            2 and 3 for Ambisonics proper.
#   opus2    the 2-channel control (200 and 300 Hz, family 0), which every
#            browser decodes; a surface that fails this one has a different
#            problem than the one this page is about.
#
# Bitrate: 192 kbit/s for 16 channels is 12 kbit/s per stream, which libopus
# handles for a pure tone with the ladder intact (checked with a Goertzel pass
# over the ffmpeg decode before this was committed). The surfaces under test
# decide on the OpusHead channel count and mapping family, not on bitrate, and
# the low rate keeps the three embedded copies of the 16-channel clip under
# about 400 KB of base64 in total.
set -e
cd "$(dirname "$0")"

DUR=3            # seconds
FRAME_MS=20      # Opus frame duration; the page schedules WebCodecs chunks by it
BITRATE16=192k
BITRATE2=64k

if ! ffmpeg -hide_banner -encoders 2>/dev/null | grep -q '[[:space:]]libopus[[:space:]]'; then
  echo "ffmpeg has no libopus encoder (ffmpeg -encoders | grep libopus is empty)" >&2
  exit 1
fi

# -fflags/-flags +bitexact keep encoder version strings, timestamps and the
# random identifiers (Ogg stream serial, Matroska SegmentUID) out of every
# container, which is what makes a rerun byte-identical. They are OUTPUT
# options: placed before -i they would apply to the lavfi input instead and
# the files would differ on every run (that is how the first draft of this
# script behaved).
BITEXACT="-fflags +bitexact -flags +bitexact"

# 16 independent sines, one per channel, 0.5 amplitude each
EXPR=""
for k in $(seq 0 15); do
  f=$((200 + 100 * k))
  EXPR="${EXPR}|0.5*sin(2*PI*${f}*t)"
done
EXPR="${EXPR#|}"

ffmpeg -y -v error \
  -f lavfi -i "aevalsrc=exprs='${EXPR}':c=16c:s=48000:d=${DUR}" \
  -c:a libopus -b:a "$BITRATE16" -frame_duration "$FRAME_MS" -mapping_family 255 \
  $BITEXACT -f ogg opus16.opus

ffmpeg -y -v error \
  -f lavfi -i "aevalsrc=exprs='0.5*sin(2*PI*200*t)|0.5*sin(2*PI*300*t)':c=stereo:s=48000:d=${DUR}" \
  -c:a libopus -b:a "$BITRATE2" -frame_duration "$FRAME_MS" \
  $BITEXACT -f ogg opus2.opus

# Remux, never re-encode. The fMP4 uses the fragmented layout a DASH packager
# emits (empty moov, 1 s fragments, moof-relative offsets) rather than a plain
# progressive MP4, because that is the shape the streaming case hands to
# Safari; decodeAudioData accepts both.
for name in opus16 opus2; do
  ffmpeg -y -v error -i "$name.opus" -c copy $BITEXACT -f webm "$name.webm"
  ffmpeg -y -v error -i "$name.opus" -c copy \
    -movflags +empty_moov+default_base_moof -frag_duration 1000000 \
    $BITEXACT -f mp4 "$name.mp4"
  python3 ogg-packets.py "$name.opus" "$FRAME_MS" > "$name-packets.json"
done

b64() { base64 < "$1" | tr -d '\n'; }
{
  echo "// Generated by make-assets.sh; do not edit. Media is CC0, see LICENSE-ASSETS."
  echo "window.ASSETS = {"
  echo "  durationS: ${DUR},"
  echo "  opus16: {"
  echo "    label: '16-channel',"
  echo "    expected: [$(seq -s, 200 100 1700)],"
  echo "    webm: \"$(b64 opus16.webm)\","
  echo "    mp4: \"$(b64 opus16.mp4)\","
  echo "    packets: $(cat opus16-packets.json)"
  echo "  },"
  echo "  opus2: {"
  echo "    label: '2-channel',"
  echo "    expected: [200,300],"
  echo "    webm: \"$(b64 opus2.webm)\","
  echo "    mp4: \"$(b64 opus2.mp4)\","
  echo "    packets: $(cat opus2-packets.json)"
  echo "  }"
  echo "};"
} > assets.js

echo "wrote (bytes):"
wc -c opus16.opus opus16.webm opus16.mp4 opus16-packets.json \
      opus2.opus opus2.webm opus2.mp4 opus2-packets.json assets.js | sed 's/^/  /'
